version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  web-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html/
    ports:
      - "8000:80"
    links:
      - db

volumes:
  db_data: